name: EAS Build & Deploy

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'android'
        type: choice
        options:
        # - all
        - android
        # - ios
      profile:
        description: 'Build profile'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - preview
        - production

jobs:
  pre-build:
    name: Pre-build Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test --if-present

  build:
    name: Build with EAS
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Expo CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build with EAS
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            eas build --platform ${{ inputs.platform }} --profile ${{ inputs.profile }} --non-interactive
          else
            eas build --platform android --profile development --non-interactive
          fi

  # deploy:
  #   name: Deploy & Update
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup Expo CLI
  #       uses: expo/expo-github-action@v8
  #       with:
  #         eas-version: latest
  #         token: ${{ secrets.EXPO_TOKEN }}

  #     - name: Publish EAS Update
  #       run: eas update --channel production --message "Update from main branch"

  #     - name: Submit to stores (Production only)
  #       if: ${{ github.event_name == 'workflow_dispatch' && inputs.profile == 'production' }}
  #       run: eas submit --platform all --profile production --non-interactive
