name: EAS Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - android
        - ios
      profile:
        description: 'Build profile'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - production

jobs:
  build:
    name: Build ${{ inputs.platform || 'all' }} platforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Expo CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Build with EAS
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            eas build --platform ${{ inputs.platform }} --profile ${{ inputs.profile }} --non-interactive
          else
            eas build --platform all --profile development --non-interactive
          fi
