name: EAS Update

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      channel:
        description: 'Update channel'
        required: true
        default: 'production'
        type: string
      message:
        description: 'Update message'
        required: false
        type: string

jobs:
  update:
    name: Publish EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Expo CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Publish EAS Update
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            eas update --channel ${{ inputs.channel }} --message "${{ inputs.message || 'Update from GitHub Actions' }}"
          else
            eas update --channel production --message "Update from main branch"
          fi
